services:
  - type: web
    name: telegram-movie-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: SHORTENER_API_KEY
        fromSecret: SHORTENER_API_KEY
      - key: SUPER_ADMIN_ID
        fromSecret: SUPER_ADMIN_ID
      - key: BOT_USERNAME
        fromSecret: BOT_USERNAME
    healthCheckPath: /health
    plan: free